name: Build Multiplatform project
on:
  pull_request:
    branches:
      - release/*

jobs:
  release-multiplatform-lib:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-12, windows-2022]
        gradle: [8.3]
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.merged == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Multiplatform project
        shell: bash
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNINGINMEMORYKEY }}
        run: ./gradlew lib:publishAllPublicationsToMavenCentralRepository