name: Build Multiplatform project
on:
  push:
    branches:
      - main
    tags:
      - release/*

jobs:
  release-multiplatform-lib:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Multiplatform project
        shell: bash
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNINGINMEMORYKEY }}
        run: |
         - ./gradlew lib:publishAllPublicationsToMavenCentralRepository
  release-multiplatform-lib-apple:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Multiplatform project
        shell: bash
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNINGINMEMORYKEY }}
        run: |
          - ./gradlew lib:publishIosArm64PublicationToMavenCentralRepository
          - ./gradlew lib:publishIosSimulatorArm64PublicationToMavenCentralRepository
          - ./gradlew lib:publishIosX64PublicationToMavenCentralRepository
          - ./gradlew lib:publishMacosArm64PublicationToMavenCentralRepository
          - ./gradlew lib:publishMacosX64PublicationToMavenCentralRepository