name: Run tests
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        gradle: [8.3]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Multiplatform project
        shell: bash
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRALUSERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRALPASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNINGINMEMORYKEY }}
        run: ./gradlew lib:allTests
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "lib/build/test-results/**/TEST-*.xml"
          output: test-summary.md
        if: always()
      - name: Upload test summary
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: test-summary.md
        if: always()